[package]
name = "blockchain-rs"
version = "0.1.0"
authors = ["Ivan Vologdin <vologdin.nsk@gmail.com>"]

[dependencies]
rust-crypto = "0.2.36"
chrono = "0.4.0"
lazy_static = "1.0"
rocket = "0.3.6"
rocket_codegen = "0.3.6"
ws = "*"
serde = "1.0.37"
serde_derive = "1.0"
serde_json = "1.0"
url = "*"
