version: '3'
services:
  node1:
    build: .
    ports:
      - "8000:8000"
    entrypoint: cargo run
    volumes:
      - /opt/project/blockchain-rs/target
      - .:/opt/project/blockchain-rs:ro
    environment:
      PEERS: "ws://node2:3012,ws://node3:3012"
    depends_on:
      - node2
      - node3
  node2:
    build: .
    ports:
      - "8001:8000"
    entrypoint: cargo run
    volumes:
      - /opt/project/blockchain-rs/target
      - .:/opt/project/blockchain-rs:ro
  node3:
    build: .
    ports:
      - "8002:8000"
    entrypoint: cargo run
    volumes:
      - /opt/project/blockchain-rs/target
      - .:/opt/project/blockchain-rs:ro
